name: Java Gradle compilation and Testing

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Project
    if: ${{ !contains(github.event.head_commit.message, '[Gradle Release Plugin]') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle Info
        run: ./gradlew -version
      - name: Build with Gradle
        run: ./gradlew clean build      
        env:
            ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
            ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
            ORG_GRADLE_PROJECT_signingKey: ${{ secrets.REBIRTH_GPG_SECRET_KEY }}
            ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.REBIRTH_GPG_SECRET_KEY_PASSWORD }}        
  