name: Java Gradle publishing

on:
  push:  
    tags:
      - '*'    

jobs:
  build:
    name: Publish Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle Info
        run: ./gradlew -version
      - name: Build with Gradle
        run: ./gradlew publish  
        env:
            ORG_GRADLE_PROJECT_sonatypeTokenPassword: ${{ secrets.SONATYPE_TOKEN_PASSWORD }}
            ORG_GRADLE_PROJECT_sonatypeTokenUsername: ${{ secrets.SONATYPE_TOKEN_USERNAME }}
            ORG_GRADLE_PROJECT_signingKey: ${{ secrets.REBIRTH_GPG_SECRET_KEY }}
            ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.REBIRTH_GPG_SECRET_KEY_PASSWORD }}        
  